"""add model showroom fields

Revision ID: 8c48055f0ac9
Revises: debeeea4c4cc
Create Date: 2026-09-05 14:32:32.600293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c48055f0ac9'
down_revision = 'debeeea4c4cc'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_rigged', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('texture_info', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('texture_info')
        batch_op.drop_column('is_rigged')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
