"""initial schema

Revision ID: d9e35c5e79fc
Revises: 
Create Date: 2026-08-10 23:27:03.717929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9e35c5e79fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # citext is required before creating tables that use CITEXT columns
    # (users.username / users.email). IF NOT EXISTS keeps re-runs safe.
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('UNREAD', 'READ', 'REPLIED', 'ARCHIVED')", name='ck_contact_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index('ix_contact_status_created', ['status', 'created_at'], unique=False)

    op.create_table('model_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('page_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referer', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_index('ix_pageviews_created', ['created_at'], unique=False)
        batch_op.create_index('ix_pageviews_path_created', ['path', 'created_at'], unique=False)

    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ADMIN', 'USER')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('polygon_count', sa.Integer(), nullable=True),
    sa.Column('vertex_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('polygon_count >= 0', name='ck_models_polycount'),
    sa.CheckConstraint('vertex_count >= 0', name='ck_models_vertcount'),
    sa.ForeignKeyConstraint(['category_id'], ['model_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index('ix_models_featured', ['is_featured'], unique=False, postgresql_where='is_published AND deleted_at IS NULL')
        batch_op.create_index('ix_models_public', ['is_published'], unique=False, postgresql_where='deleted_at IS NULL')

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('profile_image', sa.String(length=512), nullable=True),
    sa.Column('resume_url', sa.String(length=512), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_owner', sa.String(length=120), nullable=True),
    sa.Column('github_repo', sa.String(length=200), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_featured', ['is_featured'], unique=False, postgresql_where='is_published AND deleted_at IS NULL')
        batch_op.create_index('ix_projects_public', ['is_published'], unique=False, postgresql_where='deleted_at IS NULL')

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('proficiency', sa.SmallInteger(), nullable=True),
    sa.Column('years_experience', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('proficiency >= 0 AND proficiency <= 100', name='ck_skills_proficiency'),
    sa.CheckConstraint('years_experience >= 0', name='ck_skills_years'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_skills_user_name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index('ix_skills_user_order', ['user_id', 'display_order'], unique=False)

    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=320), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=512), nullable=True),
    sa.Column('default_branch', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=80), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('last_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('github_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('model_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=160), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('MODEL', 'TEXTURE', 'THUMBNAIL', 'ANIMATION', 'OTHER')", name='ck_asset_type'),
    sa.CheckConstraint('file_size >= 0', name='ck_asset_filesize'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('model_assets', schema=None) as batch_op:
        batch_op.create_index('ix_model_assets_model_type', ['model_id', 'asset_type'], unique=False)

    op.create_table('model_software',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', 'software_id')
    )
    with op.batch_alter_table('model_software', schema=None) as batch_op:
        batch_op.create_index('ix_model_software_software', ['software_id'], unique=False)

    op.create_table('github_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('sha', sa.String(length=64), nullable=True),
    sa.Column('download_url', sa.String(length=1024), nullable=True),
    sa.Column('html_url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('file', 'dir')", name='ck_ghfile_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['github_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'path', name='uq_ghfile_repo_path')
    )
    with op.batch_alter_table('github_files', schema=None) as batch_op:
        batch_op.create_index('ix_ghfile_repo_parent', ['repository_id', 'parent_id'], unique=False)

    op.create_table('github_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requests_made', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCESS', 'NOT_MODIFIED', 'RATE_LIMITED', 'FAILED')", name='ck_ghsync_status'),
    sa.CheckConstraint('requests_made >= 0', name='ck_ghsync_requests'),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('github_syncs', schema=None) as batch_op:
        batch_op.create_index('ix_ghsync_repo_started', ['repository_id', 'started_at'], unique=False)

    op.create_table('model_animations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fps', sa.SmallInteger(), nullable=True),
    sa.Column('loop', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration >= 0', name='ck_animation_duration'),
    sa.CheckConstraint('fps >= 0', name='ck_animation_fps'),
    sa.ForeignKeyConstraint(['asset_id'], ['model_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'name', name='uq_animation_model_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_animations')
    with op.batch_alter_table('github_syncs', schema=None) as batch_op:
        batch_op.drop_index('ix_ghsync_repo_started')

    op.drop_table('github_syncs')
    with op.batch_alter_table('github_files', schema=None) as batch_op:
        batch_op.drop_index('ix_ghfile_repo_parent')

    op.drop_table('github_files')
    with op.batch_alter_table('model_software', schema=None) as batch_op:
        batch_op.drop_index('ix_model_software_software')

    op.drop_table('model_software')
    with op.batch_alter_table('model_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_model_assets_model_type')

    op.drop_table('model_assets')
    op.drop_table('github_repositories')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index('ix_skills_user_order')

    op.drop_table('skills')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_public', postgresql_where='deleted_at IS NULL')
        batch_op.drop_index('ix_projects_featured', postgresql_where='is_published AND deleted_at IS NULL')

    op.drop_table('projects')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index('ix_models_public', postgresql_where='deleted_at IS NULL')
        batch_op.drop_index('ix_models_featured', postgresql_where='is_published AND deleted_at IS NULL')

    op.drop_table('models')
    op.drop_table('users')
    op.drop_table('software')
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_index('ix_pageviews_path_created')
        batch_op.drop_index('ix_pageviews_created')

    op.drop_table('page_views')
    op.drop_table('model_categories')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_status_created')

    op.drop_table('contact_messages')
    op.execute('DROP EXTENSION IF EXISTS citext')
    # ### end Alembic commands ###
