"""add model viewer transform

Revision ID: debeeea4c4cc
Revises: d9e35c5e79fc
Create Date: 2026-08-11 13:39:46.261891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debeeea4c4cc'
down_revision = 'd9e35c5e79fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_x', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('position_y', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('position_z', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rotation_x', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rotation_y', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rotation_z', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('scale_x', sa.Float(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('scale_y', sa.Float(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('scale_z', sa.Float(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('scale_z')
        batch_op.drop_column('scale_y')
        batch_op.drop_column('scale_x')
        batch_op.drop_column('rotation_z')
        batch_op.drop_column('rotation_y')
        batch_op.drop_column('rotation_x')
        batch_op.drop_column('position_z')
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    # ### end Alembic commands ###
